<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="106760" started-at="2016-08-03T10:26:04Z" finished-at="2016-08-03T10:27:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="106760" started-at="2016-08-03T10:26:04Z" finished-at="2016-08-03T10:27:50Z">
      <class name="com.pearson.pscautomation._212app.LoginLogoutTests">
        <test-method status="FAIL" signature="setUp()[pri:0, instance:com.pearson.pscautomation._212app.LoginLogoutTests@1b2e768]" name="setUp" is-config="true" duration-ms="0" started-at="2016-08-03T15:56:04Z" finished-at="2016-08-03T15:56:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.pearson.pscautomation.framework.BaseTestCase.setUp(BaseTestCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="testLogin()[pri:0, instance:com.pearson.pscautomation._212app.LoginLogoutTests@1b2e768]" name="testLogin" duration-ms="2" started-at="2016-08-03T15:57:50Z" finished-at="2016-08-03T15:57:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:com.pearson.pscautomation._212app.LoginLogoutTests@1b2e768]" name="tearDown" is-config="true" duration-ms="0" started-at="2016-08-03T15:57:50Z" finished-at="2016-08-03T15:57:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.pearson.pscautomation._212app.LoginLogoutTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
